#containers.py 

reception_containers=[
     ('agar_contacto', 'Placa de contacto'),
    ('agar_strip', 'Tira de agar'),
    ('bag_con_medio', 'Bolsa con medio de enriquecimiento'),
    ('bag_estéril', 'Bolsa estéril'),
    ('bag_stomacher', 'Bolsa para Stomacher'),
    ('bijou_bottle', 'Frasco Bijou'),
    ('bottle_hdpe', 'Botella HDPE estéril'),
    ('bottle_polipropileno', 'Botella de polipropileno'),
    ('bottle_rosca', 'Botella con tapa de rosca'),
    ('bottle_thiosulfate', 'Botella con tiosulfato de sodio'),
    ('capsula_filtrante', 'Cápsula de filtración estéril'),
    ('coliformes_bottle', 'Frasco para prueba de coliformes'),
    ('container_bioseguro', 'Contenedor bioseguro'),
    ('container_muestra', 'Contenedor para muestra'),
    ('cryovial', 'Vial criogénico'),
    ('dippas', 'Tubo Dippas'),
    ('esponja_con_medio', 'Esponja con medio'),
    ('esponja_estéril', 'Esponja estéril'),
    ('filtro_jeringa', 'Filtro de jeringa estéril'),
    ('filtro_unidad', 'Unidad de filtración estéril'),
    ('frasco_estéril', 'Frasco estéril'),
    ('hisopo_con_medio', 'Hisopo con medio de transporte'),
    ('hisopo_estéril', 'Hisopo estéril'),
    ('jeringa_estéril', 'Jeringa estéril'),
    ('matraz_estéril', 'Matraz estéril'),
    ('microplaca', 'Placa de microtitulación'),
    ('placa_agar', 'Placa con medio de cultivo'),
    ('portaobjetos', 'Portaobjetos'),
    ('recipiente_muestra', 'Recipiente para muestra'),
    ('recipiente_solidos', 'Recipiente estéril para sólidos'),
    ('recipiente_superficie', 'Recipiente para muestras de superficie'),
    ('slide_agar', 'Portaobjetos con agar'),
    ('sobres_estériles', 'Sobre estéril'),
    ('spoon_container', 'Contenedor con cucharilla'),
    ('swab_plastico', 'Swab plástico estéril'),
    ('tapón_rosca', 'Tapón con rosca estéril'),
    ('tubo_con_medio', 'Tubo con medio de cultivo'),
    ('tubo_conical', 'Tubo cónico estéril'),
    ('tubo_muestra_liquida', 'Tubo para muestra líquida'),
    ('tubo_polipropileno', 'Tubo de polipropileno'),
    ('tubo_rosca', 'Tubo con tapa de rosca'),
    ('tubo_simple', 'Tubo estéril'),
    ('unidad_filtrante', 'Unidad filtrante estéril'),
    ('vaso_muestra', 'Vaso para muestra'),
    ('vial_rosca', 'Vial con tapa de rosca'),
    ('vial_simple', 'Vial estéril'),
    ('vial_septum', 'Vial con septum'),
    ('zona_contacto', 'Placa para zona de contacto'),
]