#containers.py 

reception_containers = [
    ('contact_plate', 'Placa de contacto'),
    ('agar_strip', 'Tira de agar'),
    ('enrichment_bag', 'Bolsa con medio de cultivo'),
    ('sterile_bag', 'Bolsa estéril'),
    ('stomacher_bag', 'Bolsa para Stomacher'),
    ('hdpe_bottle', 'Botella HDPE'),
    ('pp_bottle', 'Botella de polipropileno'),
    ('screwcap_bottle', 'Botella con tapa de rosca'),
    ('thiosulfate_bottle', 'Botella con tiosulfato de sodio'),
    ('filter_capsule', 'Cápsula de filtración estéril'),
    ('coliform_bottle', 'Frasco para prueba de coliformes'),
    ('biosecure_container', 'Contenedor bioseguro'),
    ('sample_container', 'Contenedor para muestra'),
    ('cryovial', 'Vial criogénico'),
    ('dippas_tube', 'Tubo Dippas'),
    ('sponge_with_media', 'Esponja con medio'),
    ('sterile_sponge', 'Esponja estéril'),
    ('syringe_filter', 'Filtro de jeringa estéril'),
    ('filter_unit', 'Unidad de filtración estéril'),
    ('sterile_bottle', 'Frasco estéril'),
    ('swab_with_media', 'Hisopo con medio de transporte'),
    ('sterile_swab', 'Hisopo estéril'),
    ('sterile_syringe', 'Jeringa estéril'),
    ('sterile_flask', 'Matraz estéril'),
    ('microtiter_plate', 'Placa de microtitulación'),
    ('agar_plate', 'Placa con medio de cultivo'),
    ('microscope_slide', 'Portaobjetos'),
    ('general_sample_container', 'Recipiente para muestra'),
    ('solids_container', 'Recipiente estéril para sólidos'),
    ('surface_container', 'Recipiente para muestras de superficie'),
    ('agar_slide', 'Portaobjetos con agar'),
    ('sterile_envelope', 'Sobre estéril'),
    ('spoon_container', 'Contenedor con cucharilla'),
    ('plastic_swab', 'Swab plástico estéril'),
    ('screw_cap', 'Tapón con rosca estéril'),
    ('tube_with_media', 'Tubo con medio de cultivo'),
    ('conical_tube', 'Tubo cónico estéril'),
    ('liquid_sample_tube', 'Tubo para muestra líquida'),
    ('pp_tube', 'Tubo de polipropileno'),
    ('screwcap_tube', 'Tubo con tapa de rosca'),
    ('sterile_tube', 'Tubo estéril'),
    ('filtration_unit', 'Unidad filtrante estéril'),
    ('sample_cup', 'Vaso para muestra'),
    ('screwcap_vial', 'Vial con tapa de rosca'),
    ('sterile_vial', 'Vial estéril'),
    ('septum_vial', 'Vial con septum'),
    ('contact_surface_plate', 'Placa para zona de contacto'),
]
